#include <Windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <deque>
#include <map>
#include <vector>
#include <Psapi.h>
#include <intrin.h>
#include <iterator>
#include <string>
#include <math.h>
#include <assert.h>
#include <cstdint>
#include <xmmintrin.h>
#include <d3d9.h>
#include <cstdint>
#include <algorithm>
#include <iomanip>
#include <random>
#include "Imgui/imgui.h"
#include "Imgui/imgui_impl_dx9.h"
#include "GSDK/definitions.h"
#include "GSDK/util/console.h"
#include "sourcesdk/tier0/basetypes.h"
#include "sourcesdk/tier0/commonmacros.h"
#include "sourcesdk/tier0/annotations.h"
#include "sourcesdk/tier1/utlflags.h"
#include "sourcesdk/mathlib/math_pfns.h" //
#include "sourcesdk/mathlib/vector2d.h"//
#include "sourcesdk/mathlib/vector.h"  //
#include "sourcesdk/mathlib/vector4d.h" //
#include "sourcesdk/mathlib/vplane.h" //
#include "sourcesdk/mathlib/mathlib.h"
#include "sourcesdk/mathlib/vmatrix.h"//
#include "sourcesdk/tier1/chucksum_crc.h"
#include "sourcesdk/tier1/checksum_md5.h"
#include "sourcesdk/tier0/memalloc.h"
#include "sourcesdk/tier1/utlliknkedlist.h" // probably drunk
#include "sourcesdk/usercmd.h"
#include "sourcesdk/globalvars_base.h"
#include "GSDK/util/offests.h"
#include "GSDK/util/patternscanning.h"
#include "GSDK/Interfaces.h"
#include "sourcesdk/vstdlib/random.h"
#include "GSDK/util/vmt.h"
#include "sourcesdk/recv.h"
#include "sourcesdk/ClientClass.h"
#include "sourcesdk/client/CHLClient.h"
#include "GSDK/util/NetVarManager.h"
#include "sourcesdk/convar.h"
#include "sourcesdk/tier1/bitsnshit/bitbuf.h"
#include "sourcesdk/tier1/bitsnshit/bitvec.h"
#include "sourcesdk/tier1/bitsnshit/bitbuf2.h"
#include "sourcesdk/color.h"
#include "sourcesdk/tier1/utlmemory.h"
#include "sourcesdk/mathlib/compressed_vector.h"
#include "sourcesdk/tier1/utlvector.h"
#include "sourcesdk/datamap.h"
#include "sourcesdk/engine/CModelInfo.h"
#include "sourcesdk/studio.h"
#include "sourcesdk/bone_setup.h"
#include "sourcesdk/tier1/utlbuffer.h"
#include "sourcesdk/tier1/KeyValues.h"
#include "LUA/LuaInterface.h"
#include "LUA/ILuaShared.h"
#include "sourcesdk/materialsystem/MaterialSystemStuff.h"
#include "sourcesdk/materialsystem/IMaterialSystem.h"
#include "sourcesdk/materialsystem/IMatRenderContext.h"
#include "sourcesdk/materialsystem/IMaterial.h"
#include "sourcesdk/engine/IRender.h"
#include "sourcesdk/INetChannelInfo.h"
#include "sourcesdk/inetchannel.h"
#include "sourcesdk/engine/net_chan.h"
#include "sourcesdk/client/ClientEntityList.h"
#include "sourcesdk/Engine.h"
#include "sourcesdk/multiplayer/multiplayer_animstate.h"
#include "sourcesdk/multiplayer/hl2mp_playeranimstate.h"
#include "sourcesdk/Entities/IClientEntity/IHandleEntity.h"
#include "sourcesdk/Entities/IClientEntity/IClientUnknown.h"
#include "sourcesdk/Entities/IClientEntity/IClientEntity.h"
#include "sourcesdk/Entities/BaseEntity.h"
#include "sourcesdk/Entities/CBaseAnimating.h"
#include "sourcesdk/Entities/CBaseCombatWeapon.h"
#include "sourcesdk/Entities/c_baseanimatingoverlay.h"
#include "sourcesdk/Entities/c_baseflex.h"
#include "sourcesdk/Entities/c_basecombatcharacter.h"
#include "sourcesdk/Entities/C_BasePlayer.h"
#include "sourcesdk/Entities/c_basehlplayer.h"
#include "sourcesdk/Entities/c_hl2mp_player.h"
#include "sourcesdk/Entities/c_gmod_player.h"
#include "sourcesdk/engine/vgui/VPanel.h"
#include "sourcesdk/engine/vgui/IInput.h"
#include "sourcesdk/engine/vgui/IInputInternal.h"
#include "sourcesdk/engine/vgui/ISystem.h"
#include "sourcesdk/engine/vgui/IScheme.h"
#include "sourcesdk/engine/vgui/IVGui.h"
#include "sourcesdk/engine/vgui/IPanel.h"
#include "sourcesdk/engine/vgui/surface.h"
#include "sourcesdk/engine/vgui/IEngineVGui.h"
#include "sourcesdk/inputsystem/IInputSystem.h"
#include "sourcesdk/engine/vgui/vgui_controls/Panel.h"
#include "sourcesdk/engine/vgui/vgui_controls/button.h"
#include "sourcesdk/engine/vgui/vgui_controls/checkbox.h"
#include "sourcesdk/engine/vgui/Frame.h"
#include "sourcesdk/engine/IVModelRender.h"
#include "sourcesdk/view_shared.h"
#include "sourcesdk/engine/RenderView.h"
#include "sourcesdk/client/IViewRender.h"
#include "sourcesdk/client/IClientMode.h"
#include "sourcesdk/engine/IEngineTrace.h"
#include "sourcesdk/engine/vgui/IEngineVGuiInternal.h"
#include "sourcesdk/engine/vgui/CEngineVGui.h"
#include "sourcesdk/inputsystem/CInput.h"
#include "sourcesdk/gamemovement.h"
#include "sourcesdk/prediction.h"
#include "GSDK/util/CPredictionSystem.h"
#include "sourcesdk/CIVPhysicsDebugOverlay.h"
#include "sourcesdk/shaderapi/ishaderapi.h"
#include "GSDK/hackvars.h"
#include "GSDK/Menu/menu.h"
#include "GSDK/hacks/hacks.h"
#include "sourcesdk/gameevents.h"
#include "GSDK/Game Events/hitmarker.h"
#include "GSDK/Hooks/IViewRender/IViewRender__RenderView.h"
#include "GSDK/Hooks/IVRenderView/IVRenderView__SceneEnd.h"
#include "GSDK/Hooks/IVModelRender/IVModelRender__DrawModelExecute.h"
#include "GSDK/Hooks/CHLClient/CHLClient__FrameStageNotify.h"
#include "GSDK/Hooks/IPanel/IPanel__PaintTraverse.h"
#include "GSDK/Hooks/IClientMode/IClientMode__CreateMove.h"
#include "GSDK/Hooks/IClientMode/IClientMode__OverrideView.h"
#include "GSDK/Hooks/IDirect3DDevice9/IDirect3DDevice9__EndScene.h"
#include "GSDK/Hooks/IDirect3DDevice9/IDirect3DDevice9__Reset.h"
#include "GSDK/Hooks/_hooks.h"
